DROP VIEW IF EXISTS
  cexplorer."AdaPots",
  cexplorer."ActiveStake",
  cexplorer."Block",
  cexplorer."Cardano",
  cexplorer."Delegation",
  cexplorer."Epoch",
  cexplorer."ShelleyEpochProtocolParams",
  cexplorer."Reward",
  cexplorer."SlotLeader",
  cexplorer."StakeDeregistration",
  cexplorer."StakePool",
  cexplorer."StakePoolOwner",
  cexplorer."StakeRegistration",
  cexplorer."StakePoolRetirement",
  cexplorer."TokenMint",
  cexplorer."TokenInOutput",
  cexplorer."Transaction",
  cexplorer."TransactionInput",
  cexplorer."TransactionOutput",
  cexplorer."Utxo",
  cexplorer."Withdrawal" CASCADE;
DROP INDEX IF EXISTS
  idx_block_hash,
  idx_ma_tx_mint_name,
  idx_ma_tx_mint_policy,
  idx_tx_hash,
  idx_tx_in_consuming_tx,
  idx_tx_out_tx;
DROP FUNCTION IF EXISTS cexplorer.utxo_set_at_block CASCADE;
